"""added access/refresh token columns to user

Revision ID: 2776baef671a
Revises: 4441aa1c17fc
Create Date: 2023-04-28 11:06:29.252463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2776baef671a'
down_revision = '4441aa1c17fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
