"""strava_connected bool

Revision ID: 46274754bf87
Revises: 68aa1357bf14
Create Date: 2023-05-08 14:49:10.731251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46274754bf87'
down_revision = '68aa1357bf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('strava_connected')

    # ### end Alembic commands ###
