"""create tables

Revision ID: 48393b3f06b5
Revises: db974e77fad0
Create Date: 2023-04-25 17:10:25.215111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48393b3f06b5'
down_revision = 'db974e77fad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_users_team_id_teams'), 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_team_id_teams'), type_='foreignkey')
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
