"""added access/refresh token columns to user

Revision ID: 633eb65f3205
Revises: 72b66a324c57
Create Date: 2023-04-28 12:55:43.946600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633eb65f3205'
down_revision = '72b66a324c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
