"""added qualified column to activities

Revision ID: 72560882a95c
Revises: d4b71349235c
Create Date: 2023-05-17 12:09:52.459628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72560882a95c'
down_revision = 'd4b71349235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('qualified')

    # ### end Alembic commands ###
