"""added access/refresh token columns to user

Revision ID: 72b66a324c57
Revises: ca52107588ea
Create Date: 2023-04-28 11:42:57.870610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b66a324c57'
down_revision = 'ca52107588ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('strava_token_expiry')

    # ### end Alembic commands ###
