"""email unique

Revision ID: 74020f76f380
Revises: 01b819cbfb7e
Create Date: 2023-04-25 20:15:49.285579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74020f76f380'
down_revision = '01b819cbfb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    # ### end Alembic commands ###
