"""strava_id unique

Revision ID: bf8a9c23cab6
Revises: 46274754bf87
Create Date: 2023-05-08 15:41:47.741777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8a9c23cab6'
down_revision = '46274754bf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_strava_id'), ['strava_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_strava_id'), type_='unique')
        batch_op.drop_column('strava_id')

    # ### end Alembic commands ###
