"""added access/refresh token columns to user

Revision ID: ca52107588ea
Revises: 2776baef671a
Create Date: 2023-04-28 11:09:48.108769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca52107588ea'
down_revision = '2776baef671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strava_refresh_token', sa.String(), nullable=True))
        batch_op.drop_column('access_token')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('strava_refresh_token')
        batch_op.drop_column('strava_access_token')

    # ### end Alembic commands ###
