"""added an ended bool to competition

Revision ID: d98fa5036b82
Revises: 17f336792077
Create Date: 2023-05-28 09:49:58.327003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98fa5036b82'
down_revision = '17f336792077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_progress', sa.Boolean(), nullable=True))
        batch_op.drop_column('ended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('in_progress')

    # ### end Alembic commands ###
